name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.13
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.13)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore App/DxfTool.sln
      
    - name: Get version
      id: get_version
      run: |
        if ("${{ github.event_name }}" -eq "workflow_dispatch") {
          $version = "${{ github.event.inputs.version }}"
        } else {
          $version = "${{ github.ref_name }}".TrimStart("v")
        }
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        echo "Building version: $version"
      shell: powershell
      
    - name: Update version in project file
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"
        $projectPath = "App/DxfTool/DxfTool.csproj"
        $content = Get-Content $projectPath
        $content = $content -replace "<AssemblyVersion>.*</AssemblyVersion>", "<AssemblyVersion>$version.0</AssemblyVersion>"
        $content = $content -replace "<FileVersion>.*</FileVersion>", "<FileVersion>$version.0</FileVersion>"
        $content = $content -replace "<Version>.*</Version>", "<Version>$version.0</Version>"
        $content = $content -replace "<ApplicationVersion>.*</ApplicationVersion>", "<ApplicationVersion>$version.0</ApplicationVersion>"
        Set-Content $projectPath $content
      shell: powershell
      
    - name: Build and package using deploy script
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"
        cd App/DxfTool
        .\deploy-website.ps1 -Version $version -WebsiteUrl "https://github.com/mniami/dxf-tools/releases"
      shell: powershell
        
    - name: Copy release files to root
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"
        Copy-Item "App/DxfTool/website-deploy/downloads/DxfTools-v$version-installer.zip" "./"
        Copy-Item "App/DxfTool/website-deploy/downloads/DxfTools-v$version-portable.zip" "./"
      shell: powershell
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name || format('v{0}', steps.get_version.outputs.VERSION) }}
        release_name: DXF Tools v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## DXF Tools Professional v${{ steps.get_version.outputs.VERSION }}
          
          ### 🚀 What's New
          - **Complete Polish Localization**: All user interface text now displays in Polish
          - **Enhanced User Experience**: Polish-speaking users can now use the application in their native language
          - **Translated Website**: Download page and documentation now available in Polish
          - **Improved Stability**: Bug fixes and performance improvements
          
          ### 📦 Download Options
          
          **Recommended: Installer Version**
          - Download `DxfTools-v${{ steps.get_version.outputs.VERSION }}-installer.zip`
          - Extract and run `Install.bat` as administrator
          - Creates desktop shortcut and installs to user directory
          
          **Portable Version**
          - Download `DxfTools-v${{ steps.get_version.outputs.VERSION }}-portable.zip`
          - Extract and run `DxfTool.exe`
          - No installation required, but manual updates needed
          
          ### 🔧 Requirements
          - Windows 10 or later
          - .NET 8 Runtime (included in self-contained builds)
          
          ### 🌍 Language Support
          - Polish (Polski) - Complete localization
          - All UI elements, messages, and dialogs in Polish
          
        draft: false
        prerelease: false
        
    - name: Upload Installer
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./DxfTools-v${{ steps.get_version.outputs.VERSION }}-installer.zip
        asset_name: DxfTools-v${{ steps.get_version.outputs.VERSION }}-installer.zip
        asset_content_type: application/zip
        
    - name: Upload Portable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./DxfTools-v${{ steps.get_version.outputs.VERSION }}-portable.zip
        asset_name: DxfTools-v${{ steps.get_version.outputs.VERSION }}-portable.zip
        asset_content_type: application/zip
